blank_issues_enabled: false
contact_links:
  - name: Question or idea
    url: https://github.com/albertolicea00/TransCoda4Windows/discussions
    about: Ask questions and discuss ideas in GitHub Discussions.
